'use strict';

// tests for multiplyNumbersForTest
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('multiplyNumbersForTest', '/handler.js', 'multiplyNumbersForTest');

describe('multiplyNumbersForTest', () => {
  before((done) => {
    done();
  });

  it('should fail if the result is wrong', () => {
    const x = 4234;
    const y = 4334;
    const result = 18350156;
    return wrapped.run({
      query: { x, y }
    }).then((response) => {
      expect(response).to.not.be.empty;
      expect(response.body).to.not.be.empty;
      expect(JSON.parse(response.body).result).to.be.eql(result);
    });
  });
});
